# coding: utf-8
# MSDK build Sconscript
#
# $LastChangedDate$
# $LastChangedBy$


import os,sys

Import('env')



# build MGui
SConscript( 'MGui/SConscript',
            exports='env' )

# build MCore
mcore_lib = SConscript( 'MCore/SConscript', exports='env' )

# build MEngine
mengine_lib = SConscript( 'MEngine/SConscript', exports='env' )



# install to prod dir
files = [mcore_lib, mengine_lib]
import thirdparty
files.append(thirdparty.libsndfile.getLibSndFileLibs(env))
inst_msdk = env.Install(os.path.join(env['proddir'],'MSDK'), files)
inst_maratis = env.Install(os.path.join(env['proddir'],'Maratis','Bin'), files)
# examples: manualuse
inst_examples = env.Install(os.path.join(env['proddir'],'Examples','ManualUse'), files)

# mac specific
if sys.platform == 'darwin':
    inst_maratis_editor = env.Install(os.path.join(env['proddir'],'Maratis','Bin','Maratis.app/Contents/MacOS'), files)
    inst_maratis_player = env.Install(os.path.join(env['proddir'],'Maratis','Bin','MaratisPlayer.app/Contents/MacOS'), files)
    inst_examples = env.Install(os.path.join(env['proddir'],'Examples','ManualUse','ManualUse.app','Contents','MacOS'), files)
