# coding: utf-8
# examples sconscript
#
# $LastChangedDate$
# $LastChangedBy$


import os,sys

Import('env')


# build maratis sample app
program = SConscript( 'ManualUse/SConscript', exports='env' )

