# coding: utf-8
# MSDK build Sconscript
#
# $LastChangedDate$
# $LastChangedBy$


import os,sys

Import('env')



# build MGui
SConscript( 'MGui/SConscript',
            exports='env' )

# build MCore
SConscript( 'MCore/SConscript',
            exports='env' )

# build MEngine
SConscript( 'MEngine/SConscript',
            exports='env' )
