# Maratis Sample app build Sconscript
# $LastChangedDate$
# $LastChangedBy$


import os, sys, fnmatch
import pyutils
import thirdparty

Import('env')
env_local = env.Clone()

# include dirs
env_local.AppendUnique(CPPPATH = ['#MSDK/MCore/Includes',
                                  '#MSDK/MEngine/Includes',
                                  '#MSDK/MGui/Includes',
								  '#Maratis/Common',
								  '#Maratis/Common/_Implements'] )
# lib dirs
env_local.AppendUnique(LIBPATH = ['../../MSDK/MaratisCore',
                                  '../../MSDK/MEngine',
                                  '../../MSDK/MCore',
                                  '../../MSDK/MGui',
                                  '../../Maratis/Common'] )
# needed libs
env_local.AppendUnique(LIBS = ['MaratisCommon',
                               'MEngine',
                               'MCore',
                               'MGui'] )

# add 3rdparty libraries parameters
thirdparty.lua.addLuaToEnv(env_local)
thirdparty.bullet.addBulletToEnv(env_local)
thirdparty.openal.addOpenALToEnv(env_local)
thirdparty.opengl.addOpenGLToEnv(env_local)
thirdparty.glee.addGleeToEnv(env_local)
thirdparty.devil.addDevilToEnv(env_local)
thirdparty.tinyxml.addTinyXmlToEnv(env_local)
thirdparty.libpng.addLibPngToEnv(env_local)
thirdparty.libjpeg.addLibJpegToEnv(env_local)
thirdparty.zlib.addZlibToEnv(env_local)
thirdparty.freetype.addFreetypeToEnv(env_local)
thirdparty.libsndfile.addLibSndFileToEnv(env_local)
if sys.platform=='darwin':
    thirdparty.cocoa.addCocoaToEnv(env_local)
if sys.platform=='win32':
    thirdparty.windows.addWindowsToEnv(env_local)

# get list of files (recursive)
files = pyutils.getFilesRecursive(Dir('.').srcnode().abspath,'*.c*')

# build application
env_local.AppendUnique(RPATH = ['@loader_path/.',
                                '@loader_path/.'])
manualuse_exe  = env_local.Program('ManualUse',files,PDB='ManualUse.pdb')

# program = manualuse_exe
# if sys.platform == 'darwin':
#     env['VERSION_NAME'] = '0.0.1'
#     env['VERSION_NUM'] = '0.0.1'
#     bundle = env.MakeBundle ( 'ManualUse.app', 
#                               program,
#                               typecode = 'APPL')
#                               # icon_file='pig_small.icns')

Return('manualuse_exe')
