# coding: utf-8
Import('env')
env_local = env.Clone()

# include dirs
env_local.AppendUnique(CPPPATH = [''] )

# additional defines
env_local.AppendUnique(CPPDEFINES = ['EXPORT_DLL'])

# get list of files
files = Glob('./*.c*')

# build library
env_local.AppendUnique(RPATH = '@rpath/libshlib2.dylib')
shlib2_lib  = env_local.SharedLibrary('shlib2',files)
