# coding: utf-8
# test lib sconscript
#
# $LastChangedDate$
# $LastChangedBy$


import os,sys

Import('env')
env_local = env.Clone()

# build libs
shlib1 = SConscript( 'shlib1/SConscript', exports={'env':env_local} )
shlib2 = SConscript( 'shlib2/SConscript', exports={'env':env_local} )
SConscript( 'stlib/SConscript',   exports={'env':env_local} )

# build calling app
program = SConscript( 'test_libcall/SConscript', exports={'env':env_local} )

if sys.platform=='darwin':
	bundle = env_local.MakeBundle ( 'LibCall.app', 
	                                program,
	                                typecode = 'APPL',
	                                resources = [shlib1,shlib2])
