# coding: utf-8
Import('env')
env_local = env.Clone()

# include dirs
env_local.AppendUnique(CPPPATH = [''] )

# additional defines
env_local.AppendUnique(CPPDEFINES = ['EXPORT_DLL'])

# get list of files
files = Glob('./*.c*')

# build library
shlib1_lib  = env_local.SharedLibrary('shlib1',files)

Return('shlib1_lib')