# coding: utf-8
Import('env')
env_local = env.Clone()

# include dirs
env_local.AppendUnique(CPPPATH = [''] )

# additional defines
env_local.AppendUnique(CPPDEFINES = ['EXPORT_DLL'])

# get list of files
files = Glob('./*.c*')

# build library
# print '$TARGET'
# print env_local.subst('$TARGET')
env_local.AppendUnique(RPATH = '@rpath/libshlib1.dylib')
shlib1_lib  = env_local.SharedLibrary('shlib1',files)
